"""fix highscores

Revision ID: 0446d468114b
Revises: 7611ba4e560a
Create Date: 2022-06-04 15:52:07.166303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0446d468114b'
down_revision = '7611ba4e560a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
