"""Add tables

Revision ID: 169b78ff1820
Revises: 6d1e353fcb35
Create Date: 2022-04-15 13:14:04.526850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169b78ff1820'
down_revision = '6d1e353fcb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
