"""add question accuracies

Revision ID: 1cba60bfdc28
Revises: e7f2ff6ff7c5
Create Date: 2022-07-10 20:00:47.637079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cba60bfdc28'
down_revision = 'e7f2ff6ff7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyset_questions', sa.Column('correct_count', sa.Integer(), nullable=True))
    op.add_column('studyset_questions', sa.Column('wrong_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyset_questions', 'wrong_count')
    op.drop_column('studyset_questions', 'correct_count')
    # ### end Alembic commands ###
