"""added profile_picture_index

Revision ID: 7611ba4e560a
Revises: 86e9c378ac62
Create Date: 2022-05-27 22:38:45.804615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7611ba4e560a'
down_revision = '86e9c378ac62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_index')
    # ### end Alembic commands ###
