"""added highscores

Revision ID: 86e9c378ac62
Revises: b9b6ea00fd0f
Create Date: 2022-05-15 22:45:21.095218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e9c378ac62'
down_revision = 'b9b6ea00fd0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
