"""profile pic index

Revision ID: e7f2ff6ff7c5
Revises: 0446d468114b
Create Date: 2022-06-04 16:19:51.052015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f2ff6ff7c5'
down_revision = '0446d468114b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
