"""message

Revision ID: ed6bea0ca986
Revises: 6d1e353fcb35
Create Date: 2022-04-16 05:47:43.288478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6bea0ca986'
down_revision = '6d1e353fcb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('studyset_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_set', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=4096), nullable=True),
    sa.Column('answers', sa.ARRAY(sa.String(length=1000)), nullable=True),
    sa.ForeignKeyConstraint(['study_set'], ['study_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyset_questions')
    op.drop_table('study_sets')
    op.drop_table('users')
    # ### end Alembic commands ###
