"""added highscores

Revision ID: fbe45fc49844
Revises: fa233a9d2df5
Create Date: 2022-05-15 21:30:53.477673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe45fc49844'
down_revision = 'fa233a9d2df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('fishillionare_highscore', sa.Integer(), nullable=True),
    sa.Column('foodfight_highscore', sa.Integer(), nullable=True),
    sa.Column('dogeball_highscore', sa.Integer(), nullable=True),
    sa.Column('thefloorislava_highscore', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('high_scores')
    # ### end Alembic commands ###
