/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Geo_Salmon: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
  };
};

export function Fish(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/Fish.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Geo_Salmon.geometry}
        material={materials.lambert2SG}
      />
    </group>
  );
}

useGLTF.preload("/models/Fish.glb");