"""Added user table

Revision ID: 50a9c934be46
Revises: 
Create Date: 2023-10-01 14:25:40.919007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a9c934be46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('high_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('fishillionare_highscore', sa.BigInteger(), nullable=True),
    sa.Column('foodfight_highscore', sa.BigInteger(), nullable=True),
    sa.Column('dogeball_highscore', sa.BigInteger(), nullable=True),
    sa.Column('thefloorislava_highscore', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('study_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('studyset_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_set', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=4096), nullable=True),
    sa.Column('answers', sa.ARRAY(sa.String(length=1000)), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_set'], ['study_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyset_questions')
    op.drop_table('study_sets')
    op.drop_table('high_scores')
    op.drop_table('users')
    # ### end Alembic commands ###
